# Generated by Django 3.1.13 on 2021-08-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empployee',
            new_name='Employee',
        ),
    ]
